"""add Messages

Revision ID: 446e8d21f6e2
Revises: c264c2f16ba0
Create Date: 2023-04-15 15:21:31.585681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446e8d21f6e2'
down_revision = 'c264c2f16ba0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
