"""add

Revision ID: 46d43b3225d4
Revises: 8607fb8cff03
Create Date: 2023-04-19 13:53:57.302511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d43b3225d4'
down_revision = '8607fb8cff03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('target_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'target_date')
    # ### end Alembic commands ###
